#!/usr/bin/env bash
# This script installs nginx and returns a page containing
# the string "hello world!" when requested using curl.
sudo apt-get update -y && \
sudo apt-get -y install nginx
if [ "$?" -eq 0]
then
	echo -e \
"http {
	root /var/www/school;
	index index.html;
	server {
		listen 80;
		location \ {
		}
	}
}
evnts {
}" > /etc/nginx/nginx.conf
	mkdir -p /var/www/school
	echo "Hello World!" > /var/www/school/index.html
	service nginx start
	if [ "$?" -ne 0]
	then
		"problem starting nginx"
		exit 1
	fi
else
	echo "could not install nginx"
	exit 1
fi
exit 0
