#!/usr/bin/env bash
# This script displays numbers from 1 to 100,
# replacing any multiple of 3 by "Fizz",
# multiple of 5 by "Buzz" and
# multiple of both 3 and 5 by "FizzBuzz"
for i in {1..100};
do
	if ((i%3 == 0)) && ((i%5 == 0));
	then
		echo "FizzBuzz"
	elif ((i%3 == 0));
	then
		echo "Fizz"
	elif ((i%5 == 0));
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
