#!/usr/bin/env bash
# This script that loops from 1 to 10 and: displays "bad luck" and "good luck" for the 4th and 8th loop iteration respectively and "Best School" for the other iterations.
i=1
while ((i <= 10));
do
	if ((i == 4));
	then
		echo "bad luck"
	elif ((i == 8));
	then
		echo "good luch"
	else
		echo "Best School"
	fi
	((i++))
done
