#!/usr/bin/env bash
# This file/script displays the time for 12 hours and 59 minutes:
# it displays hours from 0 to 12 and minutes from 1 to 59
h=0
while ((h <= 12));
do
	echo "Hour: $h"
	m=1
	while ((m <= 59));
	do
		echo "$m"
		((m++))
	done
	((h++))
done
