#!/usr/bin/env bash
# This script displays the current directory in list format,
# where only part of the name after firsr dash is displayed"
for file in $(ls);
do
	echo "$file" | cut -d "-" -f2
done
