#!/usr/bin/env bash
# This script displays the current directory in list format,
# where only part of the name after firsr dash is displayed"
filelist="$(ls)"
for file in $filelist;
do
	echo "$file" | cut -d "-" -f2
done
